# oierfinder.py 的查询配置文件
# 使用 null 表示无限制 (无穷大或无穷小)
# 空列表 [] 表示不限制该项

# =====================
#   OIer 级别的限制
# =====================

# 限制初中入学年份区间 [min, max]
# 示例: 查找 2015 年到 2017 年入学的学生
enroll_year_range: [2015, 2017]

# 限制当前年级区间 [min, max]
# 说明:
#   - 入学前: [null, 0]
#   - 小学: [1, 6]
#   - 初中: [7, 9]
#   - 高中: [10, 12]
#   - 毕业后: [13, null]
# 示例: 查找当前是高中生的选手
# grade_range: [10, 12] 可以取消注释


# =====================
#   Record 级别的限制
# =====================
# OIer 必须拥有满足下面 *所有* 条件组的记录。
# 每个条件组内是 "AND" 关系，条件组之间是 "AND" 关系。
# 即：必须有一个记录满足第一个条件组，*并且* 有一个记录满足第二个条件组，以此类推。
records:
  # --- 第一个记录条件组 ---
  # 寻找在 2022-2023 年间，在浙江或江苏获得过 NOI 金牌或银牌的记录
  -
    province: ["浙江", "江苏"]
    year_range: [2022, 2023]
    level_range: ["金牌", "银牌"]
    # score_range: [null, null] # 不限制分数
    # rank_range: [1, 100] # 限制排名前100

  # --- 第二个记录条件组 ---
  # 并且，该选手还必须拥有在 2021 年 NOIP 中获得一等奖，且分数大于等于 200 分的记录
  -
    year_range: [2021, 2021]
    # 假设 'NOIP提高' 的 contest.type 在数据库里就是这个名字
    # contest_type: ["NOIP提高"] # 如果需要限制比赛类型，可以取消注释
    level_range: ["一等奖"]
    score_range: [200, null] # 分数 >= 200
